---
# tasks file for dawn

- include: main-linux.yml
  when: dawn_setup_system

- include: main-debian-devtools.yml

# Fail2ban scans log files (e.g. /var/log/apache/error_log) and bans IPs that show
# the malicious signs -- too many password failures, seeking for exploits, etc.
# https://www.fail2ban.org/wiki/index.php/Main_Page
- name: Install fail2ban
  apt: name=fail2ban state=present
  when: dawn_install_fail2ban

# Remote terminal application that allows roaming, supports intermittent connectivity,
# and provides intelligent local echo and line editing of user keystrokes.
# https://mosh.org/
- name: Install mosh
  action: apt pkg=mosh state=installed
  when: dawn_install_mosh == true
